# Generated by Django 3.0.2 on 2020-01-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0002_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
