# Generated by Django 3.0.2 on 2020-02-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-title']},
        ),
        migrations.AlterModelOptions(
            name='linkgroup',
            options={'ordering': ['-name']},
        ),
    ]
